###### Main Service ######
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-mainservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: acmeair-main-deployment
  template:
    metadata:
      labels:
        name: acmeair-main-deployment
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
    spec:
      containers:
        - name: acmeair-mainservice-java
          image: quay.io/mmondics/acmeair-mainservice-java-manifest:manifest-b0ca901de2049a08ddfe3ef6084f95b2f8d59c07
          ports:
            - containerPort: 9080
            - containerPort: 9443
          imagePullPolicy: Always
          env:
            - name: USERNAME
              value: admin
            - name: PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-main-service
spec:
  ports:
    - port: 9080
  selector:
    name: acmeair-main-deployment
  template:
    spec:
      containers:
        "0":
          image: quay.io/mmondics/acmeair-mainservice-java-manifest:manifest-b0ca901de2049a08ddfe3ef6084f95b2f8d59c07
