apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-bookingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: acmeair-booking-deployment
  template:
    metadata:
      labels:
        name: acmeair-booking-deployment
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
    spec:
      containers:
      - name: acmeair-bookingservice-java
        image: quay.io/mmondics/acmeair-bookingservice-java:manifest-micro4
        ports:
          - containerPort: 9080
          - containerPort: 9443
        imagePullPolicy: Always
        env:
        - name: USERNAME
          value: admin
        - name: PASSWORD
          value: password
        - name: MONGO_HOST
          value: acmeair-booking-db
        - name: ACMEAIR_STACKAA_AUTH_URL
          value: "http://acmeair-auth-service:9080/auth"
        - name: ACMEAIR_STACKAA_CUSTOMER_URL
          value: "http://acmeair-customer-service:9080/customer"
        - name: ACMEAIR_STACKAA_FLIGHT_URL
          value: "http://acmeair-flight-service:9080/flight"
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 20
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 120
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-booking-service
spec:
  ports:
    - port: 9080
  selector:
    name: acmeair-booking-deployment
---
##### Booking Database  #####
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: acmeair-booking-db
  name: acmeair-booking-db
spec:
  ports:
  - name: "27017"
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: acmeair-booking-db
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-booking-db
  namespace: acmeair-rhacm-persistent
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rootsquash-nfs
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-booking-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: acmeair-booking-db
  strategy: {}
  template:
    metadata:
      labels:
        name: acmeair-booking-db
    spec:
      volumes:
        - name: acmeair-booking-db-1
          emptyDir: {}
        - name: pvc-booking-db
          persistentVolumeClaim:
            claimName: pvc-booking-db
      containers:
      - image: quay.io/mmondics/acmeair-mongo:manifest-v1
        name: acmeair-booking-db
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        volumeMounts:
          - name: acmeair-booking-db-1
            mountPath: /data/configdb
          - name: pvc-booking-db
            persistentVolumeClaim:
              claimName: pvc-booking-db
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-booking-db
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /srv/ocp/atsocpd1/mongodb
    server: 192.168.176.67
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rootsquash-nfs
  volumeMode: Filesystem