apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-customerservice
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"kubevirt.io/v1","kind":"VirtualMachine","name":"rhel9-mongodb"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: acmeair-customer-deployment
  template:
    metadata:
      labels:
        name: acmeair-customer-deployment
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
    spec:
      containers:
      - name: acmeair-customerservice-java
        image: quay.io/mmondics/acmeair-customerservice-java:manifest-micro4
        ports:
          - containerPort: 9080
          - containerPort: 9443
        imagePullPolicy: Always
        env:
        - name: USERNAME
          value: admin
        - name: PASSWORD
          value: password
        - name: MONGO_HOST
          value: acmeair-customer-db
        - name: SECURE_SERVICE_CALLS
          value: 'true'
        - name: ACMEAIR_STACKAA_AUTH_URL
          value: "http://acmeair-auth-service:9080/auth"
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 120
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-customer-service
spec:
  ports:
    - port: 9080
  selector:
    name: acmeair-customer-deployment
---
apiVersion: v1
kind: Service
metadata:  
  name: acmeair-customer-db
  namespace: acmeair
spec:
  ports:
  - name: "27017"
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    kubevirt.io/domain: rhel9-mongodb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   creationTimestamp: null
#   name: acmeair-customer-db
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       name: acmeair-customer-db
#   strategy: {}
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         name: acmeair-customer-db
#     spec:
#       volumes:
#         - name: acmeair-customer-db-1
#           emptyDir: {}
#         - name: acmeair-customer-db-2
#           emptyDir: {}
#       containers:
#       - image: quay.io/mmondics/acmeair-mongo:manifest-v1
#         name: acmeair-customer-db
#         ports:
#         - containerPort: 27017
#           protocol: TCP
#         resources: {}
#         volumeMounts:
#           - name: acmeair-customer-db-1
#             mountPath: /data/configdb
#           - name: acmeair-customer-db-2
#             mountPath: /data/db
#       restartPolicy: Always
# status: {}