name: test-actions

env: 
  QUAY_USERNAME: mmondics
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
  # QUAY_PASSWORD: ${{ secrets.REDHAT_PASSWORD }} #use for on-prem quay
  REDHAT_USERNAME: mmondics
  REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
  GIT_USERNAME: mmondics
  GIT_EMAIL: matt.mondics@ibm.com
  SMTP_USERNAME: ibmwashingtonsystemscenter@gmail.com
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  GH_TOKEN: ${{ github.token }}

  ROX_CENTRAL_ADDRESS: https://central-stackrox.apps.atsocpd1.dmz:443
  ROX_API_TOKEN: ${{ secrets.ROX_API_TOKEN }}

  APP_NAME: acmeair-mainservice-java
  MANIFEST_NAME: acmeair-mainservice-java-manifest
  Z_IMAGE_TAGS: s390x-${{ github.sha }}
  X_IMAGE_TAGS: amd64-${{ github.sha }}
  MANIFEST_IMAGE_TAG: manifest-${{ github.sha }}
  # IMAGE_REGISTRY: quay-registry-quay-openshift-operators.apps.atsocppa.dmz/mmondics
  IMAGE_REGISTRY: quay.io/mmondics
  
on: workflow_dispatch

jobs: 
  acs-image-scan: 
    name: Scan container manifest with Red Hat Advanced Cluster Security
    runs-on: [self-hosted, linux, s390x]
    environment: openshift
    needs: update-app-yaml
    continue-on-error: true
    
    # Image scan is initated on self-hosted IBM Z runner.
    # Image scan is performed by ACS server running on IBM Z.
    steps:
    - name: install roxctl cli        
      run: | 
        curl -O https://mirror.openshift.com/pub/rhacs/assets/4.3.0/bin/Linux/roxctl-s390x
        chmod +x roxctl-s390x
        ln -s roxctl-s390x roxctl
      continue-on-error: true
    - name: deployment-check
      run: |
        ./roxctl --insecure-skip-tls-verify deployment check --endpoint ${{ env.ROX_CENTRAL_ADDRESS }} -f ./acmeair/deployments/deploy-acmeair-mainservice-java.yaml 2>&1 | tee deployment_check.txt
    - name: image-scan
      run: |
        ./roxctl --insecure-skip-tls-verify image scan --endpoint ${{ env.ROX_CENTRAL_ADDRESS }} --image ${{ env.IMAGE_REGISTRY }}/${{ env.MANIFEST_NAME }}:${{ env.MANIFEST_IMAGE_TAG }} 2>&1 | tee image_scan.txt
    - name: image-check
      run: |
        ./roxctl --insecure-skip-tls-verify image check --endpoint ${{ env.ROX_CENTRAL_ADDRESS }} --image ${{ env.IMAGE_REGISTRY }}/${{ env.MANIFEST_NAME }}:${{ env.MANIFEST_IMAGE_TAG }} 2>&1 | tee image_check.txt
    
    # Send results of security scans through email.
    - name: Send email 
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{ env.SMTP_USERNAME }}
        password: ${{ env.SMTP_PASSWORD }}
        # Subject of mail message
        subject: Security Scan for image ${{ env.IMAGE_REGISTRY }}/${{ env.MANIFEST_NAME }}:${{ env.MANIFEST_IMAGE_TAG }}
        to: matt.mondics@ibm.com
        from: Matt Mondics <matt.mondics@ibm.com>
        attachments: deployment_check.txt,image_scan.txt,image_check.txt
        # Body of mail message (might be a filename prefixed with file:// to read from)
        body: |
          Red Hat Advanced Cluster Security scans for image:
          ${{ env.IMAGE_REGISTRY }}/${{ env.MANIFEST_NAME }}:${{ env.MANIFEST_IMAGE_TAG }}
          
          See attachments for deployment check, image check, and image scan.
          
          Update the application code to remediate security findings described in the attached files.
          
          Per IBM security practices, failed security scans do not prevent commits to development branches, but they will prevent merging to main branches.
