name: test-actions

env: 
  QUAY_USERNAME: mmondics
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
  REDHAT_USERNAME: mmondics
  REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
  GIT_USERNAME: mmondics
  GIT_EMAIL: matt.mondics@ibm.com
  Z_IMAGE_TAGS: s390x-${{ github.sha }}
  X_IMAGE_TAGS: amd64-${{ github.sha }}
  MANIFEST_IMAGE_TAG: manifest-${{ github.sha }}
  ROX_CENTRAL_ADDRESS: https://central-stackrox.apps.atsocpd2.dmz:443
  #ROX_API_TOKEN: ${{ secrets.ROX_API_TOKEN }}
  IMAGE_REGISTRY: quay.io/mmondics
  APP_NAME: acmeair-mainservice-java
  MANIFEST_NAME: acmeair-mainservice-java-manifest
  SMTP_USERNAME: ibmwashingtonsystemscenter@gmail.com
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  
on: workflow_dispatch
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          # token: ${{ secrets.PAT }}
          commit-message: Update container image to ${{ env.IMAGE_REGISTRY }}/${{ env.MANIFEST_NAME }}:${{ env.MANIFEST_IMAGE_TAG }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: DevSecOps
          delete-branch: false
          title: 'Update container image to ${{ env.IMAGE_REGISTRY }}/${{ env.MANIFEST_NAME }}:${{ env.MANIFEST_IMAGE_TAG }}'
          body: |
            - Auto-generated by [create-pull-request][1]
          assignees: mmondics
          reviewers: mmondics
          draft: false
