name: Build, Scan and Rollout Multiarchitecture Containers

env: 
  QUAY_USERNAME: mmondics
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
  # QUAY_PASSWORD: ${{ secrets.REDHAT_PASSWORD }} #use for on-prem quay
  REDHAT_USERNAME: mmondics
  REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
  GIT_USERNAME: mmondics
  GIT_EMAIL: matt.mondics@ibm.com
  SMTP_USERNAME: ibmwashingtonsystemscenter@gmail.com
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  GH_TOKEN: ${{ github.token }}

  ROX_CENTRAL_ADDRESS: https://central-stackrox.apps.atsocpd1.dmz:443
  ROX_API_TOKEN: ${{ secrets.ROX_API_TOKEN }}

  APP_NAME: acmeair-mainservice-java
  MANIFEST_NAME: acmeair-mainservice-java-manifest
  Z_IMAGE_TAGS: s390x-${{ github.sha }}
  X_IMAGE_TAGS: amd64-${{ github.sha }}
  MANIFEST_IMAGE_TAG: manifest-${{ github.sha }}
  # IMAGE_REGISTRY: quay-registry-quay-openshift-operators.apps.atsocppa.dmz/mmondics
  IMAGE_REGISTRY: quay.io/mmondics

# on:
#   push:
#     paths:
#       - acmeair/source/acmeair-mainservice-java/src/main/webapp/*
#     branches:
#       - DevSecOps
# on: workflow_dispatch

jobs:
  s390x-build-and-push: 
    name: s390x build and push to Quay
    runs-on: [self-hosted, linux, s390x, native]
    environment: openshift

    steps:
    - name: Checkout
      id: checkout
      # checkout@v2 should be used until s390x runner version is updated
      uses: actions/checkout@v1
      with:
        ref: DevSecOps

    # build the app package for s390x
    - name: mvn clean package
      run: |
        mvn clean package -f ./acmeair/source/acmeair-mainservice-java/pom.xml

    # build the container image for s390x
    - name: podman build
      run: |
        podman version
        podman login registry.redhat.io -u ${{ env.REDHAT_USERNAME }} -p ${{ secrets.REDHAT_PASSWORD }}
        podman build -t ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}:${{ env.Z_IMAGE_TAGS }} ./acmeair/source/acmeair-mainservice-java

    # push the s390x container image to repo
    - name: Push to Registry 
      id: push-to-registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ env.APP_NAME }}
        tags: ${{ env.Z_IMAGE_TAGS }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.QUAY_USERNAME }}
        password: ${{ env.QUAY_PASSWORD }}
        tls-verify: false